language: dart

dart:
  - 2.0.0
  - dev
  
before_install:
  - chmod +x ./tool/travis.sh

install:
  - gem install coveralls-lcov

script: ./tool/travis.sh

after_success:
  - coveralls-lcov var/lcov.info

env:
  - DARTANALYZER_FLAGS=--fatal-warnings

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
