name: graphql_builder
description: Generate GraphQL queries in dart.
version: 1.0.0
homepage: https://github.com/SahandAkbarzadeh/graphql_builder
author: Sahand <email@example.com>

dependencies:
  coveralls: ^5.3.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
